#!/usr/bin/env bash
# This script reads /etc/passwd and displays username, user id, and home directory

while read -r line
do
    echo "$line" | cut -d: -f1,3,6 --output-delimiter=:
done < /etc/passwd
